apiVersion: v1
kind: Pod
metadata:
  name: kubelet1
  labels:
    role: myrole
  namespace: kubeletens1
spec:
  containers:
    - name: linux-pause-1
      image: docker.io/library/alpine:latest
      command: ["top"]
    - name: web
      image: nginx
      securityContext:
        privileged: true
      ports:
      - name: web
        containerPort: 80
        protocol: TCP
